### ISSUE TITLE
fix/annotation mouseover

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#268]
when hovering annotation icons in measureBasedView, nothing is being displayed. The call fails with:

```
app.js:1 ReferenceError: annotation is not defined
    at ctor.<anonymous> (app.js:1:1238973)
    at Object.each (app.js:1:57164)
    at ctor.annotationFilterChanged (app.js:1:1238609)
    at ctor.<anonymous> (app.js:1:1234246)
    at ctor.each (app.js:1:285275)
    at ctor.annotationFilterChanged (app.js:1:1234227)
    at ctor.annotationFilterChanged (app.js:1:1244825)
    at ctor.annotationsLoaded (app.js:1:1302369)
    at ctor.<anonymous> (app.js:1:1302216)
    at f (app.js:1:62334)
```

**Comment by bwbohl** [comment]
magically it doesn't happen here anymore, closing
